### ISSUE TITLE
Plagiarism Warning

### ISSUE THREAD

**Issue by aniketsingh200344** [AmruthaSri852/Attend_to_engage#1]
Your GitHub Repository is totally copied from the following link:  https://github.com/shubhamkumar27/Face_recognition_based_attendance_system. 

This is totally unfair. You call yourself a "Mentee of Microsoft Engage Intern"?. You don't have the rights to copy paste the things from someone else repository to your repository To win the project competition of "Microsoft Engage Intern". You project is completely plagiarized.
I would request the complete organization of "Microsoft Engage Intern" to look into the issue and I would request them to select the people who is working hard and giving the original projects.

Thanks....
Jzt Humans....

**Comment by nk2017321** [comment]
Yeah Bro correctly said. I completely agree with you. It is true that GitHub is an open source community but copy pasting the entire project of someone else by just changing the email to "amruthasriamaravati852@gmail.com" and by removing the screenshot of face reorganization(which was previously added) doesn't mean that it's your project.
